Add indexed 8 color level
KyoriPowered/ansi pull request #36
Opened 2023-09-26 16:50 UTC by Vankka

Adds https://github.com/KyoriPowered/ansi/issues/35

2023-09-27 10:44 UTC, rymiel approved these changes

2023-09-27 18:43 UTC, zml2008 requested changes
just one small thing, otherwise looks good

2023-09-27 18:43 UTC, zml2008 commented on src/main/java/net/kyori/ansi/ColorLevel.java
> +   * @since 1.0.4
```suggestion
   * @since 1.1.0
```

2023-09-28 01:54 UTC, zml2008 approved these changes

2023-10-04 02:52 UTC, merged